# Generated by Django 4.2 on 2023-05-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session_year',
            new_name='session_year_id',
        ),
    ]
